name: Publish

on:
  release:
    types: [ published ]
    
permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  publish:
    name: "Build, Archive & Upload"
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release --no-self-contained -p:Version=${{ github.event.release.tag_name }} -p:DebugType=None -p:UseAppHost=false -o ./pub-out DragonFruit.OnionFruit.Deploy.csproj

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'pub-out/DragonFruit.OnionFruit.Deploy.dll'

      - name: Archive
        run: cd pub-out && zip -r ../onionfruit-deploy.zip .

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: onionfruit-deploy.zip
